# Generated by Django 5.0.7 on 2024-08-04 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_country', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=10, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('screen_size', models.PositiveIntegerField()),
                ('available', models.BooleanField()),
                ('manufacturing_country', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.brand')),
            ],
        ),
    ]
