# Generated by Django 5.0.7 on 2024-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_phone_screen_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
