# Generated by Django 5.0.7 on 2024-08-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_alter_phone_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='brand_country',
        ),
    ]
